############################# Base configuration #############################
baseURL = "https://nolski.github.io/open-work-megalist/"
title = "Open Work Mega List"
theme = "inventory"
enableEmoji = true
enableGitInfo = true

# Google Analytics
# googleAnalytics = "G-80FMX4TPM0"


############################# Security configuration #############################

[security]
    [security.exec]
        allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']


############################# Navigation #############################
[[menu.main]]
weight = 10
name = "FAQ"
url = "faq"

[[menu.main]]
weight = 20
name = "pages"
url = "pages"
hasChildren = true

    [[menu.main]]
    parent = "pages"
    name = "Communities"
    url = "communities"
    weight = 10





############################# Default parameters #############################
[params]
logo = ""

# OpenGraph / Twitter Card metadata
description = "The goal of this project is to get a broad understanding of the landscape of Open Work in Academia. It's this board is meant to be messy but allow for reasonably easy grouping of various organizations together, identifying key stakeholders within these organizations, and show everything in one place. It's all in progress and will hopefully result in a more structured output after a series of interviews with folks who are experts in the field of Open Work in academia."
author = "Mike Nolan, Open@RIT"
image = "images/UNI309823.jpg"

# customize color
primary_color = "#F76902"
body_color = "#D8D1C9"
text_color = "#777779"
text_color_dark = "#374EA2"
text_title_color = "#ffffff"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family (choose from https://fonts.google.com/)
font_family = "Open+Sans"

# contact form action (works with https://formspree.io)
contact_form_action = "#"

# related article number limit
article_count = 3



############################# Brand & identity #############################
[params.brand]
parent_org_name = "Rochester Institute of Technology"
parent_org_url = "https://www.rit.edu/"
parent_org_url_legal = "https://www.rit.edu/legal"

[params.footer]
mainSite = "https://openr.it"
mainSiteName = "Open@RIT"
description = "The goal of this project is to get a broad understanding of the landscape of Open Work in Academia. It's this board is meant to be messy but allow for reasonably easy grouping of various organizations together, identifying key stakeholders within these organizations, and show everything in one place. It's all in progress and will hopefully result in a more structured output after a series of interviews with folks who are experts in the field of Open Work in academia."


############################# Social links #############################
# themify icon pack : https://themify.me/themify-icons

# [[params.social]]
# icon = "ti-github"
# name = "UNICEF Open Source Inventory on GitHub"
# link = "https://github.com/unicef/inventory"
#
# [[params.social]]
# icon = "ti-twitter"
# name = "@UNICEFinnovate on Twitter"
# link = "https://twitter.com/UNICEFinnovate"


############################# Markup tweaks and customization #############################
[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = 'murphy'
tabWidth = 4

[markup.asciidocExt]
preserveTOC = true
sectionNumbers = true

# Allow unsafe HTML
[markup.goldmark.renderer]
unsafe = true


############################# Related Articles #############################
[taxonomies]
  alert = "alerts"
  category = "categories"
  downloadable = "downloadBtn"




#######################################################################################
#                             Multilingual configurations                             #
#######################################################################################

############################# English #############################
[Languages.en]
languageName = "en"
languageCode = "en-us"
weight = 1
home = "Home"
copyright = "Creative Commons BY-SA 4.0. Site theme maintained by UNICEF. Original theme, Dot, created by ThemeFisher."

# banner
[Languages.en.params.banner]
title = "Open Work Network Inventory"
subtitle = "A knowledge base of organizations, products, and platforms which support the development of Open Work in academia."
bg_image = "images/banner.jpg"
placeholder = "Have a question? Search the site here."


