---
title: "ORCID"
description: ORCID provides a persistent digital identifier (an ORCID iD) that you own and control, and that distinguishes you from every other researcher.
tags: ["platform", "research", "software"]
categories: "collaboration"
downloadBtn: "true"

---
:toc:

> ORCID provides a persistent digital identifier (an ORCID iD) that you own and control, and that distinguishes you from every other researcher. You can connect your iD with your professional information — affiliations, grants, publications, peer review, and more. You can use your iD to share your information with other systems, ensuring you get recognition for all your contributions, saving you time and hassle, and reducing the risk of errors.

*https://orcid.org/*

== What do they do?

ORCID seeks to solve the issue of tracking a researchers work across their entire career.
The ORCID ID is meant to be a globally unique identifier that will always map to you.

== Why might this be important to me?

 * If you are a researcher, you may want to consider making an account and using it as a "Single Sign On" option for other websites related to your research.

== Considerations to make

None

